### ISSUE TITLE
Upgrade bson to ^0.5.0

### ISSUE THREAD

**Issue by ratson** [wegolook/joi-objectid#4]
Test is broken after upgrade

**Comment by nlindley** [comment]
The module does not use `equals` outside of the test. This bug seems related to mongodb/js-bson#193. I don’t know if there’s a great solution besides just rewriting the assertion. Let me investigate this a little more this evening since upgrading to ^0.5 could be a breaking change. I’ll probably end up releasing 0.5 support as v2.

**Comment by nlindley** [comment]
I will be holding off on an upgrade to version 0.5 support until hearing about mongodb/js-bson#199.

**Comment by nlindley** [comment]
The bug was fixed in the 1.0 branch. https://github.com/mongodb/js-bson/commit/1b7efe8956d160d3e01898e7b3a82ae630317128

While I’d rather wait for 1.0 to be released, if 0.5 is needed sooner, I will accept a PR that supports 0.5 and it can have its own major version.
